# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [1]:
import numpy as np
from debugpy.common.json import array

In [4]:
numbers=[1,2,3,4,5]
res=[element1 + element2 for element1,element2 in zip(numbers,numbers)]
print(res)

[2, 4, 6, 8, 10]


In [5]:
array=np.array([1,2,3,4])
result= array + array
print(result)


[2 4 6 8]


In [6]:
print(np.int8(42))
print(np.int16(42))
print(np.int32(42))
print(np.int64(42))

print(np.float16(42))
print(np.float32(42))
print(np.float64(42))

print(np.complex64(42+42j))

print(np.bool_(True))

42
42
42
42
42.0
42.0
42.0
(42+42j)
True


In [16]:
 import time 
 import sys

In [11]:
my_list=list(range(100000000))
start_time=time.time()
new_list= [element+2 for element in my_list]
print(f"List time is: {time.time()-start_time}")

my_array = np.arange(100000000)
start_time=time.time()
new_array= my_array *2
print(f"Array time is: {time.time()-start_time}")

List time is: 11.172430992126465
Array time is: 0.6262421607971191


In [17]:
my_list = list(range(1000000))
print(sys.getsizeof(my_list))
my_array = np.arange(1000000)
print(sys.getsizeof(my_array))

8000056
4000112


In [18]:
array_8bit = np.arage(100000, dtype=np.int8)
array_16bit = np.arange(100000, dtype=np.int16)

AttributeError: module 'numpy' has no attribute 'arage'

In [19]:
arr_1d=np.array([1,2,3,4,5])
print("shape ", arr_1d.shape)

shape  (5,)


In [22]:
arr_2d = np.array([[1, 2], [3, 4]])
print("shape ", arr_2d.shape)

shape  (2, 2)


In [24]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr)
print(arr.shape)
arr_2=arr.reshape(2,4)
print(arr_2)
arr3=arr.reshape(2,2,2)
print(arr3)
print(arr3.shape)


[1 2 3 4 5 6 7 8]
(8,)
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [25]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [27]:
np.linspace(10,50,30)

array([10.        , 11.37931034, 12.75862069, 14.13793103, 15.51724138,
       16.89655172, 18.27586207, 19.65517241, 21.03448276, 22.4137931 ,
       23.79310345, 25.17241379, 26.55172414, 27.93103448, 29.31034483,
       30.68965517, 32.06896552, 33.44827586, 34.82758621, 36.20689655,
       37.5862069 , 38.96551724, 40.34482759, 41.72413793, 43.10344828,
       44.48275862, 45.86206897, 47.24137931, 48.62068966, 50.        ])

In [29]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [32]:
np.random.rand(4,15)

array([[0.23248825, 0.53964509, 0.92154968, 0.26361148, 0.2942021 ,
        0.96355353, 0.59684127, 0.07603242, 0.33064018, 0.84725706,
        0.94741261, 0.73732632, 0.99539611, 0.11055689, 0.11337538],
       [0.31125124, 0.45730548, 0.22902538, 0.74038682, 0.69624213,
        0.85843913, 0.57397475, 0.23970598, 0.37810511, 0.43956936,
        0.9371265 , 0.84348873, 0.70175178, 0.45612452, 0.40140479],
       [0.56194263, 0.50070574, 0.15621869, 0.25904304, 0.50125088,
        0.44400252, 0.48083451, 0.41523483, 0.05608614, 0.35491434,
        0.17290376, 0.29652837, 0.18863452, 0.56928136, 0.60697897],
       [0.31204377, 0.93568604, 0.45907665, 0.55681436, 0.31238177,
        0.97226029, 0.58046273, 0.19809021, 0.86707564, 0.45551252,
        0.84119878, 0.98950953, 0.09716721, 0.83396372, 0.64272436]])

In [53]:
ceva=np.random.rand(4,4,5,6,7,8,9,0)

In [46]:
ceva.shape

(4, 4, 5, 6, 7, 8, 9, 0)

In [47]:
ceva.ndim

8

In [48]:
ceva.size

0

In [49]:
ceva.dtype

dtype('float64')

In [50]:
ceva.itemsize

8

In [55]:
ceva=ceva.astype(int)

In [56]:
ceva.itemsize

4

In [57]:
altcv =np.array([1,2,3,4,5,6,7,8,9,0])
print(altcv[0])
print(altcv[-1])
print(altcv[::-1])

1
0
[0 9 8 7 6 5 4 3 2 1]


In [58]:
altcv=np.array([[1,2,3,4],[5,6,7,8]])
print(altcv[0:,:2])

[[1 2]
 [5 6]]


In [60]:
altcv = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
m=altcv %2==0
print(altcv[m])

[2 4 6 8]


In [61]:
arr1=np.array([1,2,3,4,5,6,7])
arr2=np.array([1,2,3,4,5,6,7])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[ 2  4  6  8 10 12 14]
[0 0 0 0 0 0 0]
[ 1  4  9 16 25 36 49]
[1. 1. 1. 1. 1. 1. 1.]


In [63]:
alt = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(np.max(alt))
print(alt.max())
print(np.min(alt))
print(alt.min())
print(alt.mean())
print(alt.sum())
print(alt.std())

8
8
1
1
4.5
36
2.29128784747792


imultirea matricilor

In [64]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
np.dot(a,b)

array([[ 7, 10],
       [15, 22]])